### ISSUE TITLE
Getting quote from Kyber returns validation error

### ISSUE THREAD

**Issue by KjetilVaa** [0xProject/0x-api#123]
## Expected Behavior

Request:
GET https://api.0x.org/swap/v0/quote?buyToken=DAI&sellToken=WETH&buyAmount=1000000000000000000&excludedSources=Uniswap,0x,Eth2Dai

Response:
See docs: https://0x.org/docs/api#response-1

## Current Behavior

GET https://api.0x.org/swap/v0/quote?buyToken=DAI&sellToken=WETH&buyAmount=1000000000000000000&excludedSources=Uniswap,0x,Eth2Dai

Response:
{
code: 100,
reason: "Validation Failed",
validationErrors: 
[{
field: "buyAmount",
code: 1004,
reason: "INSUFFICIENT_ASSET_LIQUIDITY"
}]
}

## Steps to Reproduce (for bugs)

By excluding all liquidity sources except Kyber, the https://api.0x.org/swap/v0/quote endpoint seems to return the same validation error independent of buyAmount and buyToken/sellToken.

**Comment by dekz** [comment]
Kyber is actually not supported as a `BUY` source. We are unable to sample it in this way. It is only available as a `SELL` source.
