### ISSUE TITLE
run 0xapi with cmd "yarn dev "  then appear error

### ISSUE THREAD

**Issue by tomdong2010** [0xProject/0x-api#261]
TSError: ⨯ Unable to compile TypeScript:
src/config.ts(233,35): error TS2551: Property 'UniswapV2' does not exist on type 'typeof ERC20BridgeSource'. Did you mean 'Uniswap'?
src/config.ts(234,35): error TS2339: Property 'UniswapV2Eth' does not exist on type 'typeof ERC20BridgeSource'.
src/config.ts(235,35): error TS2339: Property 'MultiBridge' does not exist on type 'typeof ERC20BridgeSource'.
src/config.ts(243,24): error TS2551: Property 'UniswapV2' does not exist on type 'typeof ERC20BridgeSource'. Did you mean 'Uniswap'?
src/config.ts(244,24): error TS2339: Property 'UniswapV2Eth' does not exist on type 'typeof ERC20BridgeSource'.
src/config.ts(246,24): error TS2339: Property 'MultiBridge' does not exist on type 'typeof ERC20BridgeSource'.

**Comment by tomdong2010** [comment]
i used. release 1.80

**Comment by opaolini** [comment]
Please try removing the `node_modules/` folder and run:
```
yarn cache clean
```

Before reinstalling the packages.

**Comment by tomdong2010** [comment]
ok 3k
