### ISSUE TITLE
Request quote error with non-standard tokens

### ISSUE THREAD

**Issue by NotEternal** [0xProject/0x-api#736]
## Expected Behavior

Get normal data for the swap

## Current Behavior

When I send a new request with [BNG BSC](https://bscscan.com/token/0x6010e1a66934C4D053E8866Acac720c4a093d956) token as a **sellToken** and [BUSD](https://bscscan.com/address/0xe9e7cea3dedca5984780bafc599bd69add087d56) as a **buyToken**, it returns an error without a clear reason:

```
{
  "code": 105,
  "reason": "Error",
  "values": {
    "message": "Pancake: K"
  }
}
```
A liquidity pool on [Pancakeswap](https://pancakeswap.finance/) and there everything is fine with the same amounts. I can't tell the exact amount for **BNG**, but it 100% happens with numbers more then 1_000_000 token. This token has a special commission for each transaction inside his contract. This is probably the reason for this error.

> if I do not add a GET parameter **takerAddress**, API returns the swap data, but transaction will be reverted

Example: [request](https://bsc.api.0x.org/swap/v1/quote?takerAddress=0xDA873Ff72bd4eA9c122C51a837DA3f88307D1DB5&buyToken=0xe9e7cea3dedca5984780bafc599bd69add087d56&sellToken=0x6010e1a66934C4D053E8866Acac720c4a093d956&sellAmount=1000000000000000000000000&slippagePercentage=0.2)

## Steps to Reproduce (for bugs)

```
1. Make the same request as above
```

**Comment by kimpers** [comment]
Hey @NotEternal 

Unfortunately, we currently don't support tokens with an on-transfer fee. It's on our roadmap to implement support but I cannot give an exact ETA.

**Comment by NotEternal** [comment]
ok, thanks
