### ISSUE TITLE
Expiration time type int on Signed Order different from Solidity type

### ISSUE THREAD

**Issue by JoaoCampos89** [0xProject/0x-api#89]
Postgres sql int type on expiration time field on signed order can not take values as higher as supported on solidity implementation. This may cause some orders to not be saved or broken the app (In my case launchkit-backend not start).

I recommend to change the field to bigint or clean the orders for values when the value is not supported by the database

(node:13988) UnhandledPromiseRejectionWarning: QueryFailedError: value "4215519430" is out of range for type integer
    at new QueryFailedError (C:_Desenvolvimento\Verisafe\veridex-backend\src\error\QueryFailedError.ts:9:9)
    at Query.callback (C:_Desenvolvimento\Verisafe\veridex-backend\src\driver\postgres\PostgresQueryRunner.ts:178:30)

**Comment by fabioberger** [comment]
Just ran into this as well:

```
{
    "level": "error",
    "time": 1580643007974,
    "pid": 72276,
    "hostname": "MacBook.zyxel.com",
    "msg": "Error attempting to start Order Watcher service, [QueryFailedError: value \"4215519430\" is out of range for type integer]",
    "v": 1
}
```

**Comment by fragosti** [comment]
#93
