### ISSUE TITLE
Provider error when using infura as ETHEREUM_RPC_URL

### ISSUE THREAD

**Issue by gbarcomu** [0xProject/0x-api#90]
When starting the 0x_api having a mesh node, an event-pipeline and Postgres instance I have the following error:

[1580743192226] ERROR (73580 on Pantheon1): Provider error: [object Object]                                                                                                                                                        
    Error: Provider error: [object Object]                                                                                                                                                                                         
        at /home/ethereumUser/0x/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:358:15                                                                                                                              
        at process._tickCallback (internal/process/next_tick.js:68:7) 

I am using infura as ETHEREUM_RPC_URL.

I don't know if this is a bug or infura is not supported and I need a full node.

**Comment by fragosti** [comment]
Hi @gbarcomu while we look into this, I can tell you that the 0x API does support alchemy as an RPC provider. https://alchemyapi.io/
We use their service in both dev and production so that could explain why we weren't aware of this bug.

**Comment by gbarcomu** [comment]
Hi @fragosti, thank you for your answer. It seems that there is a queue of 1500 people for using their services.

Is there any mail or forum for posting doubts? It seems that nobody answers in team@0xproject.com

Thank you,

Guillermo.

**Comment by dave4506** [comment]
I haven't been able to reproduce the issue with an INFURA link, I am betting on some of the latter updates to the repo addressing this issue; if not we can reopen this.
